### ISSUE TITLE
Had to comment out some test code in testpapi.c to get it to work

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#10]
In order to get testpapi.c to run, I had to comment out the following sections of code:
```
  /* printf ("%s: testing GPTLsetoption(PAPI_TOT_CYC,1)...\n", argv[0]); */
  /* if (GPTLsetoption (code, 1) != 0) { */
  /*   printf ("Failure\n"); */
  /*   return 3; */
  /* } */

```  

```
/* printf ("Success\n"); */
  /* printf ("%s: testing reasonableness of PAPI counters...\n", argv[0]); */
  /* if (pc[0] < 1 || pc[0] > 1.e8) { */
  /*   printf ("Suspicious PAPI_TOT_CYC value=%lld for 1e6 additions\n", pc[0]); */
  /*   return 5; */
  /* } else { */
  /*   printf ("Success\n"); */
  /* } */

```

**Comment by edhartnett** [comment]
The C build system is working reasonably well now, see PR #8. Waiting on resolution of issue #13 before proceeding with Fortran library.

**Comment by edhartnett** [comment]
OK, I am just picking this issue to work on first since it is my oldest one.

I uncommented the first section of code, and it causes a test failure like this:

```
testpapi: Testing PAPI interface...
./testpapi: testing getting event code for PAPI_TOT_CYC...
Success
./testpapi: testing GPTLsetoption(PAPI_TOT_CYC,1)...
GPTL: canenable: event PAPI_TOT_CYC not available on this arch
GPTL error:GPTL_PAPIsetoption: Can't enable event 
GPTL error:GPTLsetoption: failure to enable option -2147483589
Failure
```

So the PAPI_TOT_CYC option is not available on this architecture.

Is that expected?

Is there a way we can detect in the configure whether PAPI_TOT_CYC is available on the architecture of the build system? If so, we can change this test so it knows whether or not it should expect PAPI_TOT_CYC to be settable.

**Comment by pmucci** [comment]
Hi.

Check your /proc/sys/kernel/perf_event_paranoid setting.

Philip J. Mucci
Minimal Metrics LLC
+1 415.841.3577 (global)
+46 72.172.2581 (direct)
phil@minimalmetrics.com <mailto:phil@minimalmetrics.com>

**Comment by edhartnett** [comment]
OK, sorry, @pmucci can you expand on that suggestion? Not sure what you mean.

**Comment by jmrosinski** [comment]
Ed;

Looks like recent linux distros are tightening up security in a way that
can prevent PAPI from collecting performance data. On my home Linuxmint
system, indeed the command

% cat /proc/sys/kernel/perf_event_paranoid"

returns 3. This web page:

https://superuser.com/questions/980632/run-perf-without-root-rights

explains that even 2 won't let unpriv users collect performance data, and 3
is probably even more restrictive than that. Phil can answer whether PAPI
requires "raw tracepoint access" (what "perf_event_paranoid=1" disallows),
but please try either of the following (also described in the above web
page) and see if the problem goes away:

% sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'

or

% sudo sh -c 'echo 0 >/proc/sys/kernel/perf_event_paranoid'

Jim

**Comment by edhartnett** [comment]
So we need a way to figure this out in configure.

If the correct conditions are not met, then we just turn off PAPI?

**Comment by jmrosinski** [comment]
I would say yes, disable PAPI in that case since it's an optional addition
to GPTL. Would it be possible in "configure" to print a message explaining
that the reason PAPI was disabled is the setting in
/proc/sys/kernel/perf_event_paranoid prevents its use, and if the user has
root privileges changing the setting to 1 or 0 may enable PAPI to work?

Jim

**Comment by jmrosinski** [comment]
Ed;

Note that GPTL has a MAC port, and MAC doesn't support the /proc
pseudo-filesystem. So for now I'd suggest having configure just run the
PAPI test on MAC without checking /proc, and disable PAPI if the test fails.

Honestly I don't know if PAPI even ostensibly works on MAC. I'll ask Phil...

Jim

**Comment by edhartnett** [comment]
Instead, we need to write the configure test so that it also works on a mac.

We want to determine whether PAPI is available or not before we run any code. So we can't run a test to see, we have to check in some other way. And usually there is a way. The code in this PR will fail on systems that don'e have the proc pseudo-filesystem. So what is a test for papi that will work on a mac?

Or do we only check this if the psuedo-filesystem exists? And if it doesn't we just always build for PAPI?

**Comment by jmrosinski** [comment]
Here's pseudo-code for what I think we need:

if (/proc/sys/kernel/perf_event_paranoid exists && its value is > 1) then
  disable PAPI and print a message as to why
else
  if (papi.h and libpapi.* exist) then
    if (PAPI test succeeds) then
      enable PAPI
    else
      disable PAPI
    endif
  else
    disable PAPI (library not found)
  endif
endif

I'm still no good at understanding where autotools looks for things like
header files and libraries (or cmake for that matter), but if it can find
papi.h and libpapi.* then configure can use these to build the test. If not
found, configure should disable PAPI and print a msg as to why (lib and/or
header not found).

Jim


Jim
