### ISSUE TITLE
Both MPI tests fail for me when run with 4 processors...

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#11]
We have two tests that should be run when MPI is present. Both fail for me for 4 procs. Not sure how many I should be trying.

The script in ctests called run_par_test.sh runs these tests. Currently the tests are both commented out. When they are working, these lines should be uncommented to run the tests as part of make check.

```
set -e
# echo
# echo "Testing MPI functionality..."
# mpiexec -n 4 ./pmpi
# echo "SUCCESS!"
# echo
# echo "Testing MPI summary..."
# mpiexec -n 4 ./summary
# echo "SUCCESS!"
exit 0
```

**Comment by jmrosinski** [comment]
Using the up-to-date version of edhartnett/GPTL.git, the code builds to the
satisfaction of "gnumake" on my laptop, but executables pmpi and summary do
not exist. Could this be why the test is failing?

**Comment by edhartnett** [comment]
Are you building with mpicc?

**Comment by jmrosinski** [comment]
Yes I did this with "env CC=mpicc" ./configure. Is that the correct way to
do it?

**Comment by edhartnett** [comment]
Look in your configure output to make sure it is using the mpicc compiler. The place to look is config.log, which contains all the output from all the things that configure does. It's your first stop when debugging configure problems.

**Comment by jmrosinski** [comment]
Yes it's using mpicc, but still no pmpi or summary created.

**Comment by edhartnett** [comment]
Send me the config.log file, and the output of ./configure && make check

**Comment by jmrosinski** [comment]
Ah, I didn't know I needed to do "make check". Instead just looked inside
ctests and saw that neither pmpi nor summary existed. "make check" creates
both pmpi and summary, then runs them but both fail.

In my (before autotools) stuff, "pmpi" should not be getting tested if
"ENABLE_PMPI" is false. Is this the case in your tests?

In my (before autotools) stuff, "summary" works and gives success status.
But in your stuff it fails. Could it maybe be again due to the ifdef
HAVE_PMPI, which is checed in summary.c? Yes I'd like to get rid of these
nasty ifdefs inside of the test codes. I'll look into that.

**Comment by edhartnett** [comment]
Howdy Jim!

OK, I have fixed it so that pmpi is not built unless you are building with MPI, and also have selected --enable-pmpi at configure time. You can see this in configure.ac here:

```
# Does the user want to turn on PMPI?
AC_MSG_CHECKING([whether PMPI is to be enabled])
AC_ARG_ENABLE([pmpi], [AS_HELP_STRING([--enable-pmpi],
              [build with PMPI capability])])
test "x$enable_pmpi" = xyes || enable_pmpi=no
AM_CONDITIONAL(ENABLE_PMPI, [test x$enable_pmpi = xyes])
AC_MSG_RESULT($enable_pmpi)
```

And in the ctests Makefile.am here:
```
# Build these tests if MPI is present.
if HAVE_MPI
check_PROGRAMS += summary
TESTS += run_par_test.sh
if ENABLE_PMPI
check_PROGRAMS += pmpi
TESTS += run_par_pmpi_test.sh
endif
endif
```

(Note the nested if statement for ENABLE_PMPI).

Make sure you do a git pull to see these changes, BTW.

For parallel builds, tests have to be run by a test script, so that mpiexec can be used to run the test. So the summary test is run by run_par_test.sh, and the pmpi test is run by run_par_pmpi_test.sh.

(These must be bourne shell scripts for maximum portability.)

When I build with parallel, summary is failing for me:

```
mpiexec -n 4 ./summary
GPTLerror: no vfprintf: fmt is GPTL: %s: not enabled

GPTLerror: no vfprintf: fmt is GPTL: %s: not enabled

GPTLerror: no vfprintf: fmt is GPTL: %s: not enabled

ed@mikado:~/tmp/GPTL/ctests$ echo $?
255
```

**Comment by edhartnett** [comment]
OK, now that I have fixed error messages, I see:

```
ed@mikado:~/tmp/GPTL/ctests$ mpiexec -n 4 ./summary
GPTL error:GPTL: init_gettimeofday: not enabled
GPTL error:GPTL: init_gettimeofday: not enabled
```

I am looking into this...

**Comment by jmrosinski** [comment]
That looks to be due to another HAVE_* missing (in this case
HAVE_GETTIMEOFDAY). Autotools needs to check for existence of the
gettimeofday() function. Or again maybe a too-old relic to even need
checking, and perhaps it's safe to just assume that gettimeofday() exists?

**Comment by edhartnett** [comment]
Stand by. I will add the check.

There is some cleanup of these options that can be done as a separate step, including even removing some. For now, let's just get the code compiling as much like the old build system as we need to...

**Comment by edhartnett** [comment]
OK, great, now run_par_test.sh passes! ;-) Do a git pull to get latest changes.

**Comment by edhartnett** [comment]
When I build with --enable-pmpi I now get the pmpi test. But when I run it, it fails:

 ```
cd ctests/
ed@mikado:~/tmp/GPTL/ctests$ mpiexec -n 4 ./pmpi
/home/ed/tmp/GPTL/ctests/.libs/pmpi: testing suite of MPI routines for auto-instrumentation via GPTL PMPI layer
MPI support level is MPI_THREAD_SINGLE
/home/ed/tmp/GPTL/ctests/.libs/pmpi: checking that there is a GPTL entry for MPI routine MPI_Ssend...
GPTL error:GPTLget_wallclock: requested timer MPI_Ssend does not exist
ed@mikado:~/tmp/GPTL/ctests$ 
```

I have traced this to the code here with the debugger:

 ```
 /* 
  ** Don't know whether hashtable entry for timername was generated with 
  ** *_instr() or not, so try both possibilities
  */
  indx = genhashidx (timername);
  ptr = getentry (hashtable[t], timername, indx);
  if ( !ptr) {
    if (sscanf (timername, "%lx", (unsigned long *) &self) < 1)
      return GPTLerror ("%s: requested timer %s does not exist\n", thisfunc, timername);

```

**Comment by edhartnett** [comment]
@jmrosinski what is the number of processors that pmpi and summary should be run for?

**Comment by jmrosinski** [comment]
Sorry for the delay I'm dealing with a bath remodel at the same time. Both
use 2 MPI tasks.

**Comment by edhartnett** [comment]
OK, I have changed to 2 for each. However the pmpi test still fails the same way.

Take as much times as you need, I have plenty of fun things to work on. ;-)

**Comment by jmrosinski** [comment]
2 things:

1) The pmpi test works with my old stuff when HAVE_MPI=yes and
ENABLE_PMPI=yes. With autotools, pmpi should not get built or run if either
of these are no.

2) I noticed some time ago when fiddling with .so vs. .a libraries that
auto-profiling doesn't work with .so files. Could that be the problem? If
so, perhaps some logic in the autotools build that says effectively:
"auto-profiling can only be enabled with a static build of the GPTL
library"?

**Comment by jmrosinski** [comment]
BTW the fact that auto-profiling doesn't work with .so files can be
verified by running "nm" on the executable. Assuming GPTL is compiled with
-g, "nm a.out" should print human-readable names associated with addresses.
I found that entries within .a libraries had these entries, but within .so
libraries did not.

**Comment by jmrosinski** [comment]
I'm sorry, I forgot how I set up MPI auto-profiling, and those last 2
comments from me are misleading at best. It's not auto-profiling using the
compiler, but rather the PMPI interface provided by most MPI libraries.
Bottom lline: I don't know why your test is failing but mine is succeeding.
If you have a look at src/clib/pmpi.c, you'll see that it manually calls,
e.g., GPTLstart("MPI_Ssend") before PMPI_Ssend.

I'll keep looking into this as well...

**Comment by edhartnett** [comment]
This MPI tests are working for me now, both with MPICH and openmpi, so I will close this ticket.
