### ISSUE TITLE
Suggest separate fortran library project

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#13]
From the point of view of the fortran programmer, it always makes sense to package the C and fortran libraries together.

But it is actually not a good idea. Instead the fortran library should be a separate package, distinctly versioned, which requires the C library to be installed.

This dramatically reduces build complexity for the libraries. It also saves people who want the C library from having to deal with the fortran library. For example, PIO uses the C library only.

Also, it will be much more rare to update the fortran library than the C library.

So I suggest we create a new project for the fortran wrappers and tests. This is what is done with other libraries that support both C and fortran, including netCDF and HDF5.

**Comment by jmrosinski** [comment]
I agree that co-mingling the Fortran with C complicates the build process, and simplifying the build/test procedure would be a very good thing. So I'd say go ahead and separate them. But since (around here anyway) almost all the use of GPTL is with Fortran code, can the separation be done in a way that only one "git checkout" needs to be done?

Also, for Fortran support, presumably the f_wrappers*.c would live in the fortran side of things since they're not needed for the C library?

**Comment by jmrosinski** [comment]
Actually I meant "git clone" not "git checkout". Too much svn history there...

**Comment by edhartnett** [comment]
OK, you can go ahead and merge the existing PR and we can continue on incrementally.

I will create a project for the fortran. To answer some questions:
* f_wrappers*.c will probably remain with C library.
* Users will not check out from git (unless they are developers), they will build from a tarball. (Do a make dist to get one.)
* After we get both libraries set up we can set up a way for users to configure and install them all at once. First we will get things working separately.

**Comment by jmrosinski** [comment]
Is there a way to merge the PR without impacting users who want to update their copies of the lib? I'd like to have everything working, tested, and documented (esp. Fortran) before making the change to master. Maybe make a branch that is identically master + the autotools changes? All my work for the foreseeable future is on the GPU code, so there won't be any nasty merging issues.

If you agree with this, is there something I need to do to enable you to create a branch in the GPTL repo? Or if I need to create it let me know.

**Comment by edhartnett** [comment]
You should first do a versioned release with the current build system. This will make the most recent code available.

Then commit the PR.

**Comment by edhartnett** [comment]
@jmrosinski there is now a fortran project on github which you should have revcieved an invitation to join.

I am stuck there getting the tests for fortran to build. Take a look and see if you can help.

**Comment by jmrosinski** [comment]
Need your help knowing what to do after "git clone". Tried "autoreconf -i" as before but that didn't work.

**Comment by edhartnett** [comment]
Yes, actually its the same build procedure.

But you must have the C library installed first:

```
cd GPTL
autoreconf -i
CC=mpicc ./configure --prefix=/home/ed/gptl
make -j check
make install

```

This will install the C library into /home/ed/gptl. (The default value us /usr/local, if you don't specify a prefix.)

Then to build the fortran library, you must tell the build where to find the C library:

``
cd GPTL-fortran
autoreconf -i
FC=mpif90 CPPFLAGS=-I/home/ed/gptl/include LDFLAGS=-L/home/ed/gptl/lib ./configure
make check
```

(If you install in /usr/local, and a general user will, you don't have to specify CPPFLAGS/LDFLAGS.)

**Comment by edhartnett** [comment]
OK, this is already done, so I will close this ticket.
