### ISSUE TITLE
Suggest full use of doxygen

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#14]
Currently there is some existing html documentation in directory doc.

I have wired up the config file to find doxygen. There is now a Doxyfile in the main directory with doxygen settings.

Doxygen gives great documentation from code comments, as long as they are formatted correctly. Comments at the head of a function should be formatted like this (example from netcdf):

```
/**
 * Set chunk cache size. Only affects files opened/created *after* it
 * is called.
 *
 * @param size Size in bytes to set cache.
 * @param nelems Number of elements to hold in cache.
 * @param preemption Premption stragety (between 0 and 1).
 *
 * @return ::NC_NOERR No error.
 * @return ::NC_EINVAL Bad preemption.
 * @author Ed Hartnett
 */
int
nc_set_chunk_cache(size_t size, size_t nelems, float preemption)
...
```
(Here's what the above looks like, when rendered in html: https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_8h.html#aa31da608c6acd921804dece6b02fac72)

This produces very nice looking documentation which can then easily be published right on github as documentation for your project.

Existing documentation can easily be folded in, so the existing documentation will complement the doxygen-generated documentation very nicely.

Next steps would include modifying the existing code to use the doxygen-style comments as shown above, and then mucking around with the build a bit more to merge the two documentation sets.

**Comment by jmrosinski** [comment]
OK I am not averse to looking into this approach. Though I will note that the existing html-based documentation is copious. Does doxygen allow for things like creation of "next page", "previous page", and randomly placed hyperlinks? What about example output from running code, such as the hpcc example in the existing html documentation?

**Comment by edhartnett** [comment]
Yes, doxygen allows all those things, easily. Nor will the existing documentation be wasted. We will fold it all together and it will be very nice.

**Comment by edhartnett** [comment]
Since this is outside the scope of converting build systems, I am going to close this ticket. I highly recommend that you convert existing documentation to doxygen (which would not be hard) and then continue with doxygen moving forward. However, I will leave this to @jmrosinski, and will close this issue.
