### ISSUE TITLE
Suggest that documentation is the only way to handle compiler flags for different compilers...

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#15]
Following the bad example of the early netCDF build system, the GPTL build system includes a lot of settings of command line stuff for different compilers. These are stored in the macros.make.* files. For example:

```
# Where to install GPTL library and include files.
# if "git" is not available, set REVNO by hand
REVNO = $(shell git describe)
INSTALLDIR = $(HOME)/gptl-$(REVNO)/aix

# Where to install man pages (if blank, defaults to $INSTALLDIR)
MANDIR = 

# C compiler: For AIX set in HAVE_MPI section because it's MPI-dependent
#CC = mpcc_r

# Whether to build debug lib or optimized lib, and associated flags
DEBUG = no
ifeq ($(DEBUG),yes)
  CFLAGS = -g -O0 -qfullpath
else
  CFLAGS = -O4 -qfullpath
endif

# Set compiler flags for non-default ABIs (e.g. 64-bit addressing). 
# Normally this can be blank.
ABIFLAGS =
...
```

This seems like a good idea, but it is not. Instead, we should leave all such flags the full responsibility of the end user. We may provide suggestions, but we really cannot provide flags. It is up to the end user to know that they must provide an MPI C compiler, for example, by setting CC. We don't try and pick for them.

We specified these kinds of flags with netcdf for many years, but it caused more problems than is solved.

The meaning of flags for different compilers can change over time and place, and we cannot know what the users' system is, except through the configure. Setting flags on a per-compiler basis is just too coarse-grained. What ends up happening is that one set of flags that worked in one case becomes enshrined as the answer, even though better or different flags may be available.

If there is a case where the code will not compile without a particular flag, let us detect that situation based on the programming feature that is failing, instead of based on the name of the compiler. Then we can decide what to do in a compiler-neutral manner which is maximally portable.

This is already accomplished with the new build system. But as it is maintained and evolves, the temptation to put in flags based on specific compilers must be resisted.

**Comment by jmrosinski** [comment]
Yes I am OK with this. The idea in my implementation was to enable novice
users to set various HAVE_* and ENABLE_* "make" macros to "yes" or "no"
depending on whether they needed the feature. For a given "yes" setting
they could then also tweak the associated flag settings if they had the
need and expertise to know how these flags needed to be changed, though
hopefully the flags will just work as is.

The "configure" approach of autotools as I understand has almost as much
capability in that the user sets various "-enable-*" and "-disable-*"
settings on the "configure" cmd line. They can even pass arguments to these
flags if necessary for example to specify paths to libraries and the like.
The only disadvantage to "configure" as I see it is it's not obvious if for
example the user wants to tweak certain compiler flags, how to do it. But
"configure" has the advantage that it can work even on brand new systems
that have never been tested. Also eliminates having to maintain an ever
expanding list of macros.make.* files.

**Comment by edhartnett** [comment]
If you look in the current config you can see examples of how we can set HAVE_* and ENABLE_* macros for both the C code (via config.h) or for makefiles (via automake conditionals). So we've got that covered and can add whatever we need to continue to expand portability or add new features.

Users specify flags by setting CFLAGS and FCFLAGS before they run configure. There they can specify whatever goofy compiler flags they want, and those flags will be used by configure and then by make.

I will close this ticket after adding a little documentation which lists the current suggested flags.

**Comment by edhartnett** [comment]
OK, first step here is to remove the INSTALL document, and put the (updated) installation instructions in the README. The reason is that the README is shown automatically in github and the installation instructions very naturally go at the top.

I will put up a PR with these changes...

**Comment by edhartnett** [comment]
OK, that PR is up. The place to put any C flag suggestions is in the Installation section of the README.

But you want to be very careful. In my experience it is not wise to the software creator to decide what flags will be used. Only the user can know their system well enough to know what flags to use.
