### ISSUE TITLE
What causes "GPTLerror: no vfprintf: fmt is GPTL: %s: not enabled"?

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#16]
I get this error message a lot. What is going on here?

`GPTLerror: no vfprintf: fmt is GPTL: %s: not enabled`

**Comment by edhartnett** [comment]
OK, never mind. It's obvious, isn't it?

I have put the following in configure.ac and now I get error messages:

```
# Check for vfprintf.
AC_CHECK_FUNC([vfprintf],
        [AC_DEFINE([HAVE_VPRINTF], [1], [vfprint function is available])])

```

**Comment by jmrosinski** [comment]
Yes I noticed that too. In my build approach look for "HAVE_VPRINTF=yes" in
macros.make.*. That's an old relic that may be completely gone in Linux
systems now. All the macros.make.* have it set to "yes" currently, but in
the past some C compilers didn't support the vprintf and vfprintf
functions. If you want to get rid of it entirely from autotools checking as
well as src/clib/util.c I'd be fine with that. I.e. eliminate the false
ifdef branch of "ifdef HAVE_VPRINTF".

**Comment by edhartnett** [comment]
I have added it to configure.ac. This PR is already big enough. ;-)

After the build is switched to autotools, we can clean things up further in additional, smaller steps.
