### ISSUE TITLE
Clean up C macros defined in configure...

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#17]
Some macros, like HAVE_VPRINTF, might no longer be needed since all available C libraries provide the required function.

In other cases we can simplify the build by switching to the standard name. For example, if we change HAVE_MPI to HAVE_LIBMPI (which configure automatically provides) then we don't need to define our own.

These changes will be deferred until after the build system has changed, and will be handled on a case by case basis.

**Comment by jmrosinski** [comment]
For sure let's get rid of what's not needed like HAVE_VPRINTF. Also yes
let's use HAVE_LIBMPI, especially if autotools provides the capability to
turn it off if the user doesn't want it (in my stuff they do this by
setting HAVE_MPI=no).

**Comment by edhartnett** [comment]
The user never has to turn off MPI.

If they want an MPI build, they provide CC=mpicc, if not CC=gcc. This determines whether MPI will be used.
