### ISSUE TITLE
Figure out whether MPI_CONST macro is needed

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#19]
In the configure.ac we have:

```
# Some newer MPI releases change the prototype of some input arguments from "void *" 
# to "const void *". The prototype for these functions inside GPTL must match the
# MPI library in use. For ENABLE_PMPI=yes, set MPI_CONST to yes or no appropriately.
#AC_DEFINE([MPI_CONST], [1], [Description])

```

Seems like changing from void * to const void * would not generate compile errors. 

Also with or without MPI_CONST defined, my builds all work. So perhaps MPI_CONST should be removed.

**Comment by jmrosinski** [comment]
I believe the problem happens when the underlying MPI library declares the
arg as void *. The fact that GPTL declares the arg as "const void *" means
it's going from more restrictive to less restrictive and causes a
compilation error. So we'd better keep this feature for now, though if I'm
wrong I'm happy to dispense with it.

**Comment by edhartnett** [comment]
Seems like the MPI interface is pretty fixed, including the const-ness of arguments. It's a standard.

Also, I just checked, and MPI_CONST does not seem to be used anywhere in the code.

**Comment by jmrosinski** [comment]
Agree it's a standard, but a new enough one that not all current MPI
implementations support it. So it'll be needed for a while. I'd love to get
rid of it ASAP but don't dare to yet.

BTW in my old stuff you'll see MPI_CONST tested inside Makefile so it is
used.

**Comment by edhartnett** [comment]
MPI_CONST does not appear in the new build system, or in any C or header file. So I will close this ticket.
