### ISSUE TITLE
manpage filenames not unique on case-insensitive filesystem

### ISSUE THREAD

**Issue by bandre-ucar** [jmrosinski/GPTL#2]
cloning GPTL on case insensitive file systems (e.g. Mac OS X, HFS+) results in problems with git because two files resolve to the same file name. Please rename one of the following files:

man/man3/GPTLprocess_namelist.3
man/man3/gptlprocess_namelist.3

Steps to reproduce problem:

tmp $ git clone https://github.com/jmrosinski/GPTL.git
Cloning into 'GPTL'...
remote: Counting objects: 4099, done.
remote: Total 4099 (delta 0), reused 0 (delta 0), pack-reused 4099
Receiving objects: 100% (4099/4099), 1.16 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3009/3009), done.
Checking connectivity... done.
tmp $ cd GPTL/
GPTL $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
modified:   man/man3/GPTLprocess_namelist.3
```

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by jmrosinski** [comment]
Done. I just deleted the lower case version.

Jim Rosinski

**Comment by bandre-ucar** [comment]
Thanks!
