### ISSUE TITLE
"configure" fails with PGI compiler suite

### ISSUE THREAD

**Issue by jmrosinski** [jmrosinski/GPTL#25]
NOTE: PGI compilers are now free. Get them here: https://www.pgroup.com/products/community.htm

I'm getting this, which I don't understand:

/bin/bash ../../libtool  --tag=CC   --mode=link mpicc  -g   -o libgptl.la -rpath /usr/local/lib libgptl_la-f_wrappers.lo libgptl_la-getoverhead.lo libgptl_la-gptl.lo libgptl_la-gptl_papi.lo libgptl_la-hashstats.lo libgptl_la-memstats.lo libgptl_la-memusage.lo libgptl_la-pmpi.lo libgptl_la-print_rusage.lo libgptl_la-pr_summary.lo libgptl_la-util.lo  -lm -lpthread -lrt -lpapi 
libtool: link: mpicc -shared  -DPIC  .libs/libgptl_la-f_wrappers.o .libs/libgptl_la-getoverhead.o .libs/libgptl_la-gptl.o .libs/libgptl_la-gptl_papi.o .libs/libgptl_la-hashstats.o .libs/libgptl_la-memstats.o .libs/libgptl_la-memusage.o .libs/libgptl_la-pmpi.o .libs/libgptl_la-print_rusage.o .libs/libgptl_la-pr_summary.o .libs/libgptl_la-util.o   -lm -lpthread -lrt -lpapi -lc  -g   -soname libgptl.so.0 -o .libs/libgptl.so.0.0.0
/usr/bin/ld: .libs/libgptl_la-f_wrappers.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
.libs/libgptl_la-f_wrappers.o: error adding symbols: Bad value
Makefile:412: recipe for target 'libgptl.la' failed

**Comment by edhartnett** [comment]
Try doing a make clean and try again.

**Comment by jmrosinski** [comment]
I'm almost positive I did that (reflexive action of mine whenever changing
compilers). But I'll try it again when I go home for lunch. Power went out
this morning at home, but I'll turn on the generator to power internet
connection (and refrigerator!) if power is still out.

FYI there is a macros.make.pgi in my old stuff which I know works.

**Comment by edhartnett** [comment]
I am installing PGI compilers now...

**Comment by jmrosinski** [comment]
Yikes now at home it works! So maybe you're right I just forgot to do "make
clean". Embarrassing...

Glad you're installing PGI. They provide an MPI lib and a module file so
you can do "module load PrgEnv-pgi" which is nice.

**Comment by edhartnett** [comment]
OK, let's close this ticket since apparently we are good to go with PGI.

**Comment by jmrosinski** [comment]
Probably OK to close since I was confused. See issue #26 though. I now see
where my confusion came from: PGI w/o MPI works fine, but PGI with MPI
gives a strange error. It says something about adding "-fPIC" but I'm not
sure that explains what the problem is.

**Comment by edhartnett** [comment]
The -fPIC error means that it was expecting a shared library and only found static libraries.

Does your mpi installation have shared libraries?

Do you have to rebuild mpi with the PGI compilers to get a compatible MPI library?

**Comment by jmrosinski** [comment]
No, I've been using the openmpi distro that came with the free PGI. It is still failing with:

/usr/bin/ld: .libs/libgptl_la-f_wrappers.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
.libs/libgptl_la-f_wrappers.o: error adding symbols: Bad value

Were you able to install PGI compilers and test on your machine?

**Comment by edhartnett** [comment]
Try doing a make distclean.

Then start over, but use --disable-shared as a configure option.

**Comment by jmrosinski** [comment]
Yes, that worked. So for some reason shared libs seem to be failing with PGI. Can we add a caveat indicating the need for --disable-shared to README or elsewhere? Once that's in place we can close this ticket.

**Comment by edhartnett** [comment]
I suspect this is a problem that is on your machine, not general. I would be pretty surprised if PGI can't build shared libs.

Try and make distclean again, and then try without --disable-shared to confirm that shared library builds do not work. Then post your config.log file and the full output of the configure and make. (Yes, it's long, that's OK.)

**Comment by jmrosinski** [comment]
It's still failing. I've commented and added the requested files in issue
#26 since it is only when enabling MPI and only when building a shared lib
that the problem occurs.

**Comment by edhartnett** [comment]
OK, let's close this ticket and track the PGI/MPI shared library issue in #26.

**Comment by jmrosinski** [comment]
Works now.
