### ISSUE TITLE
Make combined C/Fortran build project

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#28]
I can make a third project which combines the C and Fortran projects for developers and users, without any duplication of code or effort. Git submodules and autoconf work together to accomplish this magic. ;-)

**Comment by jmrosinski** [comment]
This functionality is in there, no? If so we can close this comment.

**Comment by edhartnett** [comment]
No I have to create a new github project for the combined distribution. Please leave this issue open until I do that. First I want to resolve the C library issues, then the fortran issues, then we will make a combined build.

**Comment by edhartnett** [comment]
I have done this and it seems to be working well. Take a look here:
https://github.com/NOAA-GSD/GPTL-all

@jmrosinski I will invite you as an admin to the GPTL-all repo.
