### ISSUE TITLE
master branch should be protected in github

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#29]
This is fully described here:
https://help.github.com/articles/about-protected-branches/

Basically go to settings and check the box to protect master from commits. Protect it from admins as well.

After that pull requests will be used for all changes to master. This allows for review, automatic testing, etc., and prevents accidental commits.

**Comment by jmrosinski** [comment]
Happy to do this. Should I first create a branch from master, named "develop" or something similar, before doing this?

**Comment by jmrosinski** [comment]
So, once this is done, how do we ensure pull requests go to "develop" rather than "master"?

**Comment by edhartnett** [comment]
No there is no need for develop branch.

master is only protected from command-line pushes. Pull requests do still happen to master.

So basically, protecting master just means you are forced to always use pull requests to change master.

**Comment by edhartnett** [comment]
@jmrosinski should this issue be closed?

**Comment by jmrosinski** [comment]
No not until it's actually in place. OK under the repo I went to "settings"
and see the closest thing says "Merge Button". But I don't understand those
entries so don't know what to click on (maybe "Allow merge commits"?

**Comment by edhartnett** [comment]
You can make me admin and I can do it. Or you can google I'm sure there's some tutorials out there. ;-)

**Comment by jmrosinski** [comment]
Obviously I'm a complete neophyte at this stuff. But, the docs seem to
indicate there is a difference between projects owned by an individual
(GPTL/jmrosinski is an example) and those owned by an organization
(GPTL-fortran is an example, owned by NOAA-GSD). The latter clearly has an
"admin" permitting button under "settings". The former does not, but it
does have this text:

Repositories owned by an organization can grant more granular access. For
more information, see "Access permissions on GitHub
<https://help.github.com/articles/access-permissions-on-github>."

**Comment by edhartnett** [comment]
OK, I didn't know that.

Actually I do all my repos under one organization or another, including one under my personal github account called World Domination Council. So if you don't want to transfer the repo to either GSD or NCAR, you should make an organization of your own, and transfer it to that.

**Comment by jmrosinski** [comment]
I'm going to close this since I am no longer employed or therefore a member of an organization paying for github added goodies such as test harnesses. If there's still value in protecting the master, feel free to reopen.

**Comment by rljacob** [comment]
Jim, github organizations are free.  You could create one and move the GPTL repo to it.
