### ISSUE TITLE
Can you create a tag based on 6dc3796bf3074598

### ISSUE THREAD

**Issue by sholly** [jmrosinski/GPTL#3]
We would like to include it in an upcoming cime/CESM development tag.  

Much obliged!

Jay Shollenberger

**Comment by jmrosinski** [comment]
Done. It is now tag v5.4.4. The only change vs. v5.4.3 was to remove a file
which was identical to another except for case, which caused problems on
case-insensitive machines such as MAC.

Jim Rosinski
