### ISSUE TITLE
Resovle unsupported_utils directory

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#41]
There is an unsupported_utils directory. What's that all about? Do we want to build them, or delete them from the repo?

```
 /home/ed/tmp/GPTL/unsupported_utils/cprsummary:
  total used in directory 372 available 56064748
  drwxrwxr-x 2 ed ed   4096 May 17 17:14 .
  drwxrwxr-x 4 ed ed   4096 May 17 17:14 ..
  -rw-rw-r-- 1 ed ed  10005 May 17 17:14 cpr2summaries.c
  -rw-rw-r-- 1 ed ed 109728 May 17 17:14 file1
  -rw-rw-r-- 1 ed ed 109728 May 17 17:14 file2
  -rw-rw-r-- 1 ed ed 109584 May 17 17:14 file2.modified
  -rw-rw-r-- 1 ed ed  10640 May 17 17:14 filea
  -rw-rw-r-- 1 ed ed  10877 May 17 17:14 fileb
  -rw-rw-r-- 1 ed ed    159 May 17 17:14 Makefile
```

**Comment by jmrosinski** [comment]
The "unsupported_utils/" directory is a relatively recent addition to GPTL.
Its purpose is to hold utility programs which I and others have found
useful, but don't wish to support. These codes should not be compiled as
part of the testing procedure--if something breaks in there it should not
inhibit a commit--I'll get around to fixing it or removing it later.
Functionality of the codes in there extends beyond the scope of the
supported use of GPTL, but may be useful. I'm happy to entertain ideas on a
better way to manage/maintain these codes, but would like to keep them
somewhere.

Perhaps just the name "unsupported_utils" is not sufficient to deter users'
expectations, and a README should be added indicating that things in there
may or may not work?

**Comment by edhartnett** [comment]
Currently they are not built or included in the distribution (i.e. the tarball). They exist only in the repo.

But I am disinclined to leave them there. Can we create a utils directory, move them and the script to utils, and make them part of the build? 

Looking at the code, they don't look too hard. So seems like there's not an extra support burden. Let's just include them.

**Comment by edhartnett** [comment]
OK, upon further consideration, I will leave these alone. However I advise you either support them or remove them. ;-)

I will close this issue.
