### ISSUE TITLE
Do a new release - version 6.0.0

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#43]
Once the remaining build issues are resolved, let's do a release.

The last release was v5.5.3. I suggest we call the new release 6.0.0. This will make it easy to keep track of old vs. new build systems in support and documentation.

6.0.0 is the first version that will support shared library builds everywhere. 

The 6.0.0 version is also the first version that includes the C library only, with a separate fortran library. We can release the first Fotran release as 6.0.0 as well. (But be advised, the version numbers in general will not track. You will release a lot more C library versions than Fortran versions.) Having the same major version number will make it clear that the fortran library goes with the C library.

**Comment by jmrosinski** [comment]
Agreed a release is due sooner rather than later.

What should we do about the PGI problem (fails with shared lib build)? I
have no idea what the compiler is complaining about (see latest addition to
issue #25) but --disable-shared is currently required to get a PGI build.

**Comment by edhartnett** [comment]
We can wait until the PGI issue is resolved before release, as well as any other tickets that you feel are crucial to solve before release.

**Comment by jmrosinski** [comment]
Sounds good. Were you able to install the free version of PGI (18.4 I
believe) along with openmpi so we can check if you encounter the same
problem? FYI I am running on a 64-bit Linuxmint system.

**Comment by edhartnett** [comment]
No not yet. ;-) I'm hoping you can debug this one.

**Comment by edhartnett** [comment]
Howdy Jim! I believe we should merge the outstanding PR and then do a release...

**Comment by edhartnett** [comment]
OK, I just did a release, called 5.6.0.

I also did a release of the fortran library, also called 5.6.0.

I also, also did a combined library release, GPTL-all, version 1.0.0. Installing GPTL-all gives you both the Fortran and C libraries in one install package, while keeping the two repos separate.

I will close this ticket.
