### ISSUE TITLE
Behaviour when using timer tags longer than MAX_CHARS chars

### ISSUE THREAD

**Issue by febay** [jmrosinski/GPTL#5]
I am using GPTL to time different stages of a software. The stages are named by strings, which are at maximum 512 chars long. To time a stage its name is used as GPTL start and stop tag. If a string is longer than 64 chars, GPTL fails to match the start timing with the stop timing tag, respectively the timing for this stage is not recorded.

I can make this work by adapting the `#define MAX_CHARS 64` to `#define MAX_CHARS  512` in the `private.h` file.

Nevertheless in my opinion GPTL should either warn the user (or even abort) if a tag longer than the allowed length is used (potentially expensive in time), or truncate the used tag to the allowed length (could cause ambiguous tags).

**Comment by jmrosinski** [comment]
You are right this is a bug. It works fine in Fortran but not C. I will fix it. Thank you for pointing out the problem.

**Comment by jmrosinski** [comment]
Fixed by printing a diagnostic msg in GPTLstart and failing. Chose this route to avoid adding an expensive strlen() call on every invocation of GPTLstart.

Sorry for the insanely long delay in addressing this issue. It slipped through the cracks.
