### ISSUE TITLE
missing test script in distribution

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#51]
I am getting this error in make check:

```
make[2]: Entering directory `/misc/whome/Edward.Hartnett/Downloads/gptl-all-1.0.0/GPTL/test'
PASS: tst_simple
PASS: global
make[2]: *** No rule to make target `run_par_test.sh', needed by `run_par_test.sh.log'.  Stop.
```

**Comment by jmrosinski** [comment]
The script is there and everything is working for me in branch master. I
just now did a fresh:

% git clone  git@github.com:jmrosinski/GPTL.git
% cd GPTL
% ls test/run_par_test.sh
test/run_par_test.sh
% autoreconf -i
% ./configure
% make
% make check
PASS: tst_simple
PASS: global
PASS: cygprofile
============================================================================
Testsuite summary for GPTL 5.6.0_experimental
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

So I'm not sure what's going on, or why that script isn't there for you.

**Comment by edhartnett** [comment]
Yes but the test script also needs to be included in EXTRA_DIST in the Makefile.am, so that it is packaged into the distributions. ;-)

**Comment by jmrosinski** [comment]
Assuming this isn't something that got inadvertently deleted (in which case
I'll fix it), please feel free to make/commit/push the change or issue a
PR. It's a minor enough change you can go straight to master, or you can
use "working" if you'd prefer. I just created that branch in both repos so
that broken stuff doesn't inadvertently get pushed to master. "working" is
for rapid-fire commits, but no pushes should be done to it if previously
passing tests break.

I am scrambling to get the library and infrastructure in shape for release.
Though I'm getting more familiar with autotools, currently I know next to
nothing about using it to create distributions.

**Comment by edhartnett** [comment]
We will not release without CI, I believe. Lets move to a new github org and get that going.

**Comment by jmrosinski** [comment]
CI is in there now (Travis).
