### ISSUE TITLE
need a way to turn off parallel tests

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#52]
We can't always launch parallel programs with mpiexec. Sometimes a scheduling system is in use and mpiexec can't be used.

For those machines we need a --disable-parallel-tests to allow tests to be build, and sequential tests to be run, but not parallel tests. It's then up to the user to run the parallel tests.

**Comment by jmrosinski** [comment]
All batch systems I have worked on allow batch-interactive access. The tests should work in that mode.

**Comment by edhartnett** [comment]
How do I do that?

**Comment by jmrosinski** [comment]
On theia for a 30-minute debug test I do this:

qsub -A gsd-hpcs -I -X -q debug -lnodes=1:ppn=12,walltime=00:30:00

They're moving to slurm soon and I know batch-interactive works there too,
but don't have the formula handy.

**Comment by edhartnett** [comment]
OK, let me look into how this is done with slurm and I will revisit this issue...

**Comment by jmrosinski** [comment]
All is good on this issue? If so I'll close it.

**Comment by jmrosinski** [comment]
I assume this issue is no longer a problem. Feel free to reopen if it is still an issue.
