### ISSUE TITLE
move repo to new GPTL organization, turn on travis CI

### ISSUE THREAD

**Issue by edhartnett** [jmrosinski/GPTL#53]
@jmrosinski I have created a new GitHub organization, called GPTL. I have moved the GPTL-all and GPTL-fortran repos there.

I have turned on travis CI for the GPTL-fortran repo and am trying to get that building cleanly. You can see how useful it will be.

We need to move this repo (i.e. the C library) to the new group, and then I will turn on travis. You can move it from "settings", or make me admin and I will move it for you.

Once moved, I will update the GPTL-all project to point to the repos in their new home.

**Comment by jmrosinski** [comment]
C and Fortran are now in a single repo to make things simplest for C, C++, and Fortran users.
