### ISSUE TITLE
No configure in Master 

### ISSUE THREAD

**Issue by BryanFlynt-NOAA** [jmrosinski/GPTL#59]
Hey Jim,
I checked out the master branch and tried to follow the instructions but it seems a couple things are missing.  To start there is no configure file to run.  I'm far from a AutoTools person but I read some web page and generated one.  Didn't work.  Shouldn't the configure file already be generated and included in the repo?

> aclocal
> autoconf
> ./configure
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

**Comment by edhartnett** [comment]
Instread of aclocal and autoconf, call autoreconf -i.

So:
```
autoreconf -i
./configure
make check
```

As is typical of autotools builds, the intermediate files (ex the configure file) are not stored in the repo. When a release is done (make dist) then a configure is generated for that release and put into the tarball.

**Comment by jmrosinski** [comment]
It's now a part of the latest release.
