### ISSUE TITLE
MPI_IN_PLACE does not work

### ISSUE THREAD

**Issue by bonfus** [jmrosinski/GPTL#7]
The following code does not work when the PMPI interface is used:

    program main
      use mpi
      implicit none
      integer :: myid, numprocs, namelen, rc, ierr
      integer :: ni(3), no(3)
      
      call MPI_INIT( ierr )
      call MPI_COMM_RANK( MPI_COMM_WORLD, myid, ierr )
      call MPI_COMM_SIZE( MPI_COMM_WORLD, numprocs, ierr )
      ni(:)=myid
      print *, "In place is ", MPI_IN_PLACE
      call MPI_Allreduce(MPI_IN_PLACE, ni, 3,MPI_INTEGER, MPI_MAX, MPI_COMM_WORLD, ierr)
      print *,"Result ", ni
      call MPI_FINALIZE(rc)
    end

The reason is that the pointer passed to the C implementation is not checked against the Fortran definitions of MPI_IN_PLACE (and others) and is thus considered as a memory space to source from.
Unfortunately I haven't found any `*f2c` command that could be used to check this.
The only solution that I see is to save the pointers to MPI_IN_PLACE (and other like this) at initialization time and later check in the pmpi wrapper.

**Comment by jmrosinski** [comment]
Sorry for the huge delay. I've spent some time looking at this and don't see an immediate solution. E.g. the mpich MPI implementation of MPI_Allreduce tests whether sendbuf==MPIR_F_IN_PLACE and if so sets sendbuf=MPI_IN_PLACE before issuing the "real" call to MPI_Allreduce. I don't see any portable (across MPI implementations) way to handle this in GPTL's pmpi wrapper. So for now we're stuck and MPI_IN_PLACE may or probably won't work when GPTL MPI wrapping is enabled.

Thank you for bringing up the issue though.

**Comment by jmrosinski** [comment]
MPI libs I've examined put the Fortran tests on MPI_IN_PLACE and MPI_BOTTOM directly in the Fortran wrapper itself. This means any Fortran code using these sentinels and passing them through the PMPI profiling layer will FAIL if the profiling layer implemented by the library (e.g. GPTL) doesn't do the same thing as the MPI Fortran layer.

Thus the problem found and outlined correctly by @bonfus  I've got an approach in mind and will begin implementation in GPTL. So far I've figured out how to get the address of Fortran's MPI_IN_PLACE up into GPTL's main C code. Next I'll start modifying the affected Fortran PMPI wrapper routines (written in C) to test this value (and MPI_BOTTOM) and do the right thing. Stay tuned.

**Comment by jmrosinski** [comment]
This issue should be fixed now. Haven't created a distribution yet, but checking out the master branch now includes the fix. The tag is v8.1.0. In a nutshell the fix was to implement a similar mechanism as used in e.g. mpich to test for MPI_IN_PLACE in the wrapper code before passing to the underlying C routine. A set of Fortran tests was added and "make check" tests proper behavior of MPI_IN_PLACE as passed from Fortran.

Thanks to @bonfus for finding and reporting the error.
